### ISSUE TITLE
v0.19 repeatedly throws error but is actually functioning normally

### ISSUE THREAD

**Issue by mkoohafkan** [MikhailArkhipov/vscode-r#54]
I periodically get this very long error. The error is irritating because it switches focus from Terminal to Output, but it doesn't actually seem to affect anything and my R session continues to work normally. 

> Unhandled exception. System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.R.LanguageServer.Threading.MainThread.MainThreadAwaiter.OnCompleted(Action continuation)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitOnCompleted[TAwaiter,TStateMachine](TAwaiter& awaiter, TStateMachine& stateMachine, Task`1& taskField)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 8:52:53 AM] Connection to server got closed. Server will restart.
[Error - 8:52:53 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.19\node_modules\vscode-jsonrpc\lib\common\connection.js:1044:27)
	at Object.dispose (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.19\node_modules\vscode-languageclient\lib\common\client.js:73:35)
	at LanguageClient.handleConnectionClosed (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.19\node_modules\vscode-languageclient\lib\common\client.js:2424:42)
	at LanguageClient.handleConnectionClosed (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.19\node_modules\vscode-languageclient\lib\node\main.js:155:15)
	at closeHandler (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.19\node_modules\vscode-languageclient\lib\common\client.js:2411:18)
	at CallbackList.invoke (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.19\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.19\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at closeHandler (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.19\node_modules\vscode-jsonrpc\lib\common\connection.js:256:26)
	at CallbackList.invoke (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.19\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.19\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at StreamMessageWriter.fireClose (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.19\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:42:27)
	at Socket.<anonymous> (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.19\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:75:42)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:674:12)
[Info  - 8:52:54 AM] Available R interpreters:
[Info  - 8:52:54 AM] 	[0] R 4.0.3
[Info  - 8:52:54 AM] 	[1] R 4.0.2
[Info  - 8:52:54 AM] You can specify the desired interpreter index in the R settings
[Info  - 8:52:54 AM] or provide path to R using `r.interpreterPath` setting.
[Info  - 8:52:54 AM] Selected interpreter: [0] R 4.0.3.
[Info  - 8:52:54 AM] Starting R Process with C:\LocalPrograms\R\R-4.0.3...
[Info  - 8:52:58 AM] complete in 00:04:226
[Info  - 8:52:58 AM] Building IntelliSense index...

**Comment by MikhailArkhipov** [comment]
Try https://github.com/MikhailArkhipov/vscode-r/releases/download/0.0.20/r-0.0.20.vsix. I could not repro cancellation exception, but I fixed few suspicious places.

**Comment by mkoohafkan** [comment]
I'll continue to test, but so far the new version seems to have resolved the issue. Thanks!

**Comment by mkoohafkan** [comment]
Calling this fixed. Thanks again!

**Comment by mkoohafkan** [comment]
Unfortunately this issue is not fully resolved---not sure if it resurfaced when I updated to R 4.0.4 or if I just wasn't doing the same kind of development work when I was testing v0.20. I think these errors tend to occur when R receives errors from command line interfaces; for example, I get the error fairly often when checking an R package with `devtools` and failing some tests. Example output from the latest error below. Again this is mostly just an annoyance, R continues to function normally.

```
Unhandled exception. System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.R.LanguageServer.Threading.MainThread.MainThreadAwaiter.OnCompleted(Action continuation)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitOnCompleted[TAwaiter,TStateMachine](TAwaiter& awaiter, TStateMachine& stateMachine, Task`1& taskField)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 12:45:44 PM] Connection to server got closed. Server will restart.
[Error - 12:45:44 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\connection.js:1044:27)
	at Object.dispose (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-languageclient\lib\common\client.js:73:35)
	at LanguageClient.handleConnectionClosed (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-languageclient\lib\common\client.js:2424:42)
	at LanguageClient.handleConnectionClosed (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-languageclient\lib\node\main.js:155:15)
	at closeHandler (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-languageclient\lib\common\client.js:2411:18)
	at CallbackList.invoke (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at closeHandler (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\connection.js:256:26)
	at CallbackList.invoke (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at StreamMessageWriter.fireClose (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:42:27)
	at Socket.<anonymous> (c:\Users\mkoohafk\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:75:42)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:674:12)
```

**Comment by samrickman** [comment]
Hi! I also get this error from time to time. As @mkoohafkan says, it's not a huge deal, because it just seems to switch from terminal to output but nothing actually breaks. Overall, I am loving using vscode rather than Rstudio these days.

I started my R session at 09.55 and was using it happily, and it occurred at around 13.51. This is my output

 ```
[Info  - 09:55:01] Starting R Process with C:\Program Files\R\R-4.0.4...
[Info  - 09:55:05] complete in 00:03:218
[Info  - 09:55:05] Building IntelliSense index...
[Info  - 09:55:19] complete in 00:14:210
Unhandled exception. System.OperationCanceledException: The operation was canceled.
at System.Threading.CancellationToken.ThrowOperationCanceledException()
at Microsoft.R.LanguageServer.Threading.MainThread.MainThreadAwaiter.OnCompleted(Action continuation)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitOnCompleted[TAwaiter,TStateMachine](TAwaiter& awaiter, TStateMachine& stateMachine, Task`1& taskField)
--- End of stack trace from previous location ---
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 13:51:10] Connection to server got closed. Server will restart.
[Error - 13:51:10] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\connection.js:1044:27)
	at Object.dispose (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-languageclient\lib\common\client.js:73:35)
	at LanguageClient.handleConnectionClosed (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-languageclient\lib\common\client.js:2424:42)
	at LanguageClient.handleConnectionClosed (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-languageclient\lib\node\main.js:155:15)
	at closeHandler (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-languageclient\lib\common\client.js:2411:18)
	at CallbackList.invoke (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at closeHandler (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\connection.js:256:26)
	at CallbackList.invoke (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at StreamMessageWriter.fireClose (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:42:27)
	at Socket.<anonymous> (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.20\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:75:42)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:674:12)
[Info  - 13:51:11] Available R interpreters:
[Info  - 13:51:11] 	[0] R 4.0.4
[Info  - 13:51:11] 	[1] R 3.6.3
[Info  - 13:51:11] You can specify the desired interpreter index in the R settings
[Info  - 13:51:11] or provide path to R using `r.interpreterPath` setting.
[Info  - 13:51:11] Selected interpreter: [0] R 4.0.4.

[Info  - 13:51:11] Starting R Process with C:\Program Files\R\R-4.0.4...
[Info  - 13:51:13] complete in 00:02:034
[Info  - 13:51:13] Building IntelliSense index...
[Info  - 13:51:24] complete in 00:10:653
```

I am on Windows 10. This is the output of `version`:


```
platform       x86_64-w64-mingw32
arch           x86_64
os             mingw32
system         x86_64, mingw32
status
major          4
minor          0.4
year           2021
month          02
day            15
svn rev        80002
language       R
version.string R version 4.0.4 (2021-02-15)
nickname       Lost Library Book
```

The error seems to occur more or less randomly, rather than when I am doing anything in particular. 

I am using v.0.0.20 of RTools from the vscode store, and I use `radian` in the console. My R section of settings.json contains:

```
    // R stuff
    "r.rterm.windows": "C:\\Users\\rickman\\AppData\\Local\\Programs\\Python\\Python38\\Scripts\\radian.exe",
    "r.rterm.option": [],
    "r.sessionWatcher": true,
    "files.associations": {
        "*.rmd": "markdown"
    },
```

Let me know if there's anything I can do to help isolate where the error is occurring. Alt-tabbing between R sessions in different vscode windows seems to make it happen more often - I wonder if there's a link there but I don't know what it is.

**Comment by MikhailArkhipov** [comment]
Check if 0.22 is any better

**Comment by samrickman** [comment]
Hi thanks I did upgrade - I am still getting the same issue sometimes, seemingly randomly.

```
[Info  - 15:20:40] Available R interpreters:
[Info  - 15:20:40] 	[0] R 4.0.4
[Info  - 15:20:40] 	[1] R 3.6.3
[Info  - 15:20:40] You can specify the desired interpreter index in the R settings
[Info  - 15:20:40] or provide path to R using `r.interpreterPath` setting.
[Info  - 15:20:40] Selected interpreter: [0] R 4.0.4.

[Info  - 15:20:40] Starting R Process with C:\Program Files\R\R-4.0.4...
[Info  - 15:20:43] complete in 00:03:353
[Info  - 15:20:43] Building IntelliSense index...
[Info  - 15:20:55] complete in 00:12:067
Unhandled exception. System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.R.LanguageServer.Threading.MainThread.MainThreadAwaiter.OnCompleted(Action continuation)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AwaitOnCompleted[TAwaiter,TStateMachine](TAwaiter& awaiter, TStateMachine& stateMachine, Task`1& taskField)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info  - 19:24:34] Connection to server got closed. Server will restart.
[Error - 19:24:34] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.22\node_modules\vscode-jsonrpc\lib\common\connection.js:1044:27)
	at Object.dispose (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.22\node_modules\vscode-languageclient\lib\common\client.js:73:35)
	at LanguageClient.handleConnectionClosed (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.22\node_modules\vscode-languageclient\lib\common\client.js:2424:42)
	at LanguageClient.handleConnectionClosed (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.22\node_modules\vscode-languageclient\lib\node\main.js:155:15)
	at closeHandler (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.22\node_modules\vscode-languageclient\lib\common\client.js:2411:18)
	at CallbackList.invoke (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.22\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.22\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at closeHandler (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.22\node_modules\vscode-jsonrpc\lib\common\connection.js:256:26)
	at CallbackList.invoke (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.22\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.22\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at StreamMessageWriter.fireClose (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.22\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:42:27)
	at Socket.<anonymous> (c:\Users\rickman\.vscode\extensions\mikhail-arkhipov.r-0.0.22\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:75:42)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:674:12)
[Info  - 19:24:35] Available R interpreters:
[Info  - 19:24:35] 	[0] R 4.0.4
[Info  - 19:24:35] 	[1] R 3.6.3
[Info  - 19:24:35] You can specify the desired interpreter index in the R settings
[Info  - 19:24:35] or provide path to R using `r.interpreterPath` setting.
[Info  - 19:24:35] Selected interpreter: [0] R 4.0.4.

[Info  - 19:24:35] Starting R Process with C:\Program Files\R\R-4.0.4...
[Info  - 19:24:39] complete in 00:03:458
[Info  - 19:24:39] Building IntelliSense index...
[Info  - 19:24:50] complete in 00:11:225
```

Thanks for following up. I will continue ignoring it (it's not a huge deal) and if a pattern becomes apparent I will let you know.
